# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies without running scripts
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Manually build the project
RUN npm run build

CMD ["npm", "start"]
